package model;
// Generated 2017-7-17 10:36:56 by Hibernate Tools 3.6.0.Final

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer commentid;
	private int userid;
	private int planid;
	private String text;
	private int likes;

	public Comment() {
	}

	public Comment(int userid, int planid, String text, int likes) {
		this.userid = userid;
		this.planid = planid;
		this.text = text;
		this.likes = likes;
	}

	public Integer getCommentid() {
		return this.commentid;
	}

	public void setCommentid(Integer commentid) {
		this.commentid = commentid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getPlanid() {
		return this.planid;
	}

	public void setPlanid(int planid) {
		this.planid = planid;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public int getLikes() {
		return this.likes;
	}

	public void setLikes(int likes) {
		this.likes = likes;
	}

}
