package model;
// Generated 2017-9-11 20:13:15 by Hibernate Tools 3.6.0.Final

/**
 * Planlike generated by hbm2java
 */
public class Planlike implements java.io.Serializable {

	private PlanlikeId id;
	private int point;

	public Planlike() {
	}

	public Planlike(PlanlikeId id, int point) {
		this.id = id;
		this.point = point;
	}

	public PlanlikeId getId() {
		return this.id;
	}

	public void setId(PlanlikeId id) {
		this.id = id;
	}

	public int getPoint() {
		return this.point;
	}

	public void setPoint(int point) {
		this.point = point;
	}

}
