package model;
// Generated 2017-9-11 20:13:15 by Hibernate Tools 3.6.0.Final

/**
 * PlanlikeId generated by hbm2java
 */
public class PlanlikeId implements java.io.Serializable {

	private int planid;
	private int userid;

	public PlanlikeId() {
	}

	public PlanlikeId(int planid, int userid) {
		this.planid = planid;
		this.userid = userid;
	}

	public int getPlanid() {
		return this.planid;
	}

	public void setPlanid(int planid) {
		this.planid = planid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlanlikeId))
			return false;
		PlanlikeId castOther = (PlanlikeId) other;

		return (this.getPlanid() == castOther.getPlanid()) && (this.getUserid() == castOther.getUserid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlanid();
		result = 37 * result + this.getUserid();
		return result;
	}

}
