package model;
// Generated 2017-7-10 15:39:42 by Hibernate Tools 3.6.0.Final

/**
 * Route generated by hbm2java
 */
public class Route implements java.io.Serializable {

	private String routeMongoid;
	private Routeinfo routeinfo;
	private int routedate;

	public Route() {
	}

	public Route(String routeMongoid, Routeinfo routeinfo, int routedate) {
		this.routeMongoid = routeMongoid;
		this.routeinfo = routeinfo;
		this.routedate = routedate;
	}

	public String getRouteMongoid() {
		return this.routeMongoid;
	}

	public void setRouteMongoid(String routeMongoid) {
		this.routeMongoid = routeMongoid;
	}

	public Routeinfo getRouteinfo() {
		return this.routeinfo;
	}

	public void setRouteinfo(Routeinfo routeinfo) {
		this.routeinfo = routeinfo;
	}

	public int getRoutedate() {
		return this.routedate;
	}

	public void setRoutedate(int routedate) {
		this.routedate = routedate;
	}

}
