package model;
// Generated 2017-9-11 20:13:15 by Hibernate Tools 3.6.0.Final

/**
 * RoutelikeId generated by hbm2java
 */
public class RoutelikeId implements java.io.Serializable {

	private int routeid;
	private int userid;

	public RoutelikeId() {
	}

	public RoutelikeId(int routeid, int userid) {
		this.routeid = routeid;
		this.userid = userid;
	}

	public int getRouteid() {
		return this.routeid;
	}

	public void setRouteid(int routeid) {
		this.routeid = routeid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoutelikeId))
			return false;
		RoutelikeId castOther = (RoutelikeId) other;

		return (this.getRouteid() == castOther.getRouteid()) && (this.getUserid() == castOther.getUserid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRouteid();
		result = 37 * result + this.getUserid();
		return result;
	}

}
