package model;
// Generated 2017-7-13 9:53:14 by Hibernate Tools 3.6.0.Final

/**
 * Route generated by hbm2java
 */
public class Route implements java.io.Serializable {

	private String routeMongoid;
	private Routeinfo routeinfo;
	private int routedate;
	private String location1;
	private String location2;

	public Route() {
	}

	public Route(String routeMongoid, Routeinfo routeinfo, int routedate, String location1, String location2) {
		this.routeMongoid = routeMongoid;
		this.routeinfo = routeinfo;
		this.routedate = routedate;
		this.location1 = location1;
		this.location2 = location2;
	}

	public String getRouteMongoid() {
		return this.routeMongoid;
	}

	public void setRouteMongoid(String routeMongoid) {
		this.routeMongoid = routeMongoid;
	}

	public Routeinfo getRouteinfo() {
		return this.routeinfo;
	}

	public void setRouteinfo(Routeinfo routeinfo) {
		this.routeinfo = routeinfo;
	}

	public int getRoutedate() {
		return this.routedate;
	}

	public void setRoutedate(int routedate) {
		this.routedate = routedate;
	}

	public String getLocation1() {
		return this.location1;
	}

	public void setLocation1(String location1) {
		this.location1 = location1;
	}

	public String getLocation2() {
		return this.location2;
	}

	public void setLocation2(String location2) {
		this.location2 = location2;
	}

}
