package model;
// Generated 2017-7-20 14:48:45 by Hibernate Tools 3.6.0.Final

/**
 * Routecomment generated by hbm2java
 */
public class Routecomment implements java.io.Serializable {

	private Integer commentid;
	private int userid;
	private int routeid;
	private String text;
	private int likes;

	public Routecomment() {
	}

	public Routecomment(int userid, int routeid, String text, int likes) {
		this.userid = userid;
		this.routeid = routeid;
		this.text = text;
		this.likes = likes;
	}

	public Integer getCommentid() {
		return this.commentid;
	}

	public void setCommentid(Integer commentid) {
		this.commentid = commentid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getRouteid() {
		return this.routeid;
	}

	public void setRouteid(int routeid) {
		this.routeid = routeid;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public int getLikes() {
		return this.likes;
	}

	public void setLikes(int likes) {
		this.likes = likes;
	}

}
