package model;
// Generated 2017-7-14 10:15:45 by Hibernate Tools 3.6.0.Final

/**
 * Routetag generated by hbm2java
 */
public class Routetag implements java.io.Serializable {

	private Integer routetagid;
	private int routeid;
	private int tagid;

	public Routetag() {
	}

	public Routetag(int routeid, int tagid) {
		this.routeid = routeid;
		this.tagid = tagid;
	}

	public Integer getRoutetagid() {
		return this.routetagid;
	}

	public void setRoutetagid(Integer routetagid) {
		this.routetagid = routetagid;
	}

	public int getRouteid() {
		return this.routeid;
	}

	public void setRouteid(int routeid) {
		this.routeid = routeid;
	}

	public int getTagid() {
		return this.tagid;
	}

	public void setTagid(int tagid) {
		this.tagid = tagid;
	}

}
