package model;
// Generated 2017-7-13 16:43:34 by Hibernate Tools 3.6.0.Final

/**
 * Route generated by hbm2java
 */
public class Route implements java.io.Serializable {

	private String routeMongoid;
	private int routeid;
	private int routedate;
	private String location1;
	private String location2;

	public Route() {
	}

	public Route(String routeMongoid, int routeid, int routedate, String location1, String location2) {
		this.routeMongoid = routeMongoid;
		this.routeid = routeid;
		this.routedate = routedate;
		this.location1 = location1;
		this.location2 = location2;
	}

	public String getRouteMongoid() {
		return this.routeMongoid;
	}

	public void setRouteMongoid(String routeMongoid) {
		this.routeMongoid = routeMongoid;
	}

	public int getRouteid() {
		return this.routeid;
	}

	public void setRouteid(int routeid) {
		this.routeid = routeid;
	}

	public int getRoutedate() {
		return this.routedate;
	}

	public void setRoutedate(int routedate) {
		this.routedate = routedate;
	}

	public String getLocation1() {
		return this.location1;
	}

	public void setLocation1(String location1) {
		this.location1 = location1;
	}

	public String getLocation2() {
		return this.location2;
	}

	public void setLocation2(String location2) {
		this.location2 = location2;
	}

}
