package model;
// Generated 2017-7-14 10:14:53 by Hibernate Tools 3.6.0.Final

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private Integer tagid;
	private String tagname;

	public Tag() {
	}

	public Tag(String tagname) {
		this.tagname = tagname;
	}

	public Integer getTagid() {
		return this.tagid;
	}

	public void setTagid(Integer tagid) {
		this.tagid = tagid;
	}

	public String getTagname() {
		return this.tagname;
	}

	public void setTagname(String tagname) {
		this.tagname = tagname;
	}

}
